### ISSUE TITLE
[Event] Naxx pre event (Remake)

### ISSUE THREAD

**Issue by Oroxzy** [vmangos/core#904]
**INFO:**
https://us.forums.blizzard.com/en/wow/t/naxxramas-opening-time-and-scourge-invasion-adjustments/741200

**TODO CHECKLIST:**

- [ ] **Complete rework of how the event is spawning things over the world**
- [ ] **Complete rework of the Camp spawning mechanic (Necrotic Shards and Minions)**
- [x] **Complete rework of the Necropolis to Camp (Shards) communication mechanic**
- [ ] **Updating and Fix all NPCs (As much as possible with DB scripting)**
****************************************************************************************

Spell 28234 is used as a spawn animation in this clip (not sure its exactly this spell ID but it looks like it)
https://clips.twitch.tv/CrypticFamousPuffinKappaPride

Spell 17680 is used as despawn animation:
https://clips.twitch.tv/FaintMoralGoblinTheTarFu

**!ONLY CLASSIC!**
The "submerge" animation is also missing for ghouls, but i can't find this animation:
https://clips.twitch.tv/MotionlessWanderingCardBabyRage

**Some Sniff research:**

**Ghoul/Skeleton Camp:**

**Creature** [**16338**](https://classicdb.ch/?npc=16338) (Scourge Invasion Minion, spawner, Ghoul/Skeleton)

- casting **28185** ([PH] Summon Minion parent (ghoul/skeleton))
`1. triggers: cpp script.`

**Creature** abilities [**16299**](https://classicdb.ch/?npc=16299) (Skeletal Shocktrooper)

- 17014 (Bone Shards)

**Creature** abilities [**16141**](https://classicdb.ch/?npc=16141) (Ghoul Berserker)

- **7367** (Infected Bite)

- **8599** (Enrage) used only once, near death for sure.

**Creature** ([**16141**](https://classicdb.ch/?npc=16141), [**16299**](https://classicdb.ch/?npc=16141) (Skeletal Shocktrooper)) on Spawn.
- **28234** (Minion Spawn-in) (this is probably casted after he is visible after 17680 aura ends)
- **28126** (Spirit Particles (purple))
- **28090** (Minion Despawn Timer) is casted by himself every 1-2 seconds (maybe triggered by script until necropolis destroyed)
`1. triggers: **28091** (Despawner, self) in 150 second.`

- **17680** (Spirit Spawn-out)
` 1. triggers: 60 seconds invis. (6) Apply Aura #18: Mod Invisibility (2)`

**Not sure how this works, but every minion (ghouls etc.) is using **17680** only once. I'm assuming:**
- Ghoul spawns with (auras 28090 and 28126 in creature_template confirmed in sniffs)
- 28090 triggers 28091 after 150 seconds
- 28091 triggers 17680 via [**void Spell::EffectDummy**](https://github.com/Oroxzy/core/commit/c32d83c94e509e345345eb60dbb08ee33ca2f43a)
- shortly after the cast the creature gets removed and there are no more records from its guid after then.
```
- creature_auras_update: 1602793452438 ms
- creature_destroy_time: 1602793453905 ms
- 1467 ms after aura added unit gets destroyed
```

![grafik](https://user-images.githubusercontent.com/357606/103685336-5893db00-4f8d-11eb-926a-eec972bab5e2.png)

**Casting on other creatures if near:**
- **28265** (Scourge Strike)
`1. triggers (1) Instakill.`
https://clips.twitch.tv/HelplessBreakableDeerSwiftRage

**On death?:**
- Casting **28032** (Zap Crystal)

**Creature** [**16172**](https://classicdb.ch/?npc=16172) (Damaged Necrotic Shard)
- has aura **27888** (Minion Spawner, Buttress)
```
1. triggers: 27886 (Disturb Minion Trap, Buttress) wich actives a GameObject.
2. I guess its the Necropolis, its the only object in the sniffs (gameobject_custom_anim)
```

- is casting **28449** (Camp Receives Communique) every 15 seconds
- casting **28351** (Communique, Camp-to-Relay, Death)

**Creature** [**16356**](https://classicdb.ch/?npc=16356) (Scourge Invasion Minion, finder)
- castet **28203** (Find Camp Type) once on Damaged Necrotic Shard

**Creature** [**16398**](https://classicdb.ch/?npc=16398) (Necropolis Proxy)
- is casting **28366** (Communique, Proxy-to-Relay) every 5 seconds
- casting **28351** (Communique, Camp-to-Relay, Death) 

**Creature** [**16386**](https://classicdb.ch/?npc=16386) (Necropolis Relay)
- is casting **28326** (Communique, Relay-to-Camp) every 15 seconds

**Creature** [**16421**](https://classicdb.ch/?npc=16421) (Necropolis)
- casting **28349** (Despawner, other) on **16401** (Necropolis)
- casting **28386** (Zap Necropolis)

**Creature** [**16143**](https://classicdb.ch/?npc=16143) (Shadow of Doom)
- casting **28056** (Zap Crystal Corpse)
- casting **12542** (Fear) every 15 seconds

***********************************************************************************

**Sequence i put together from sniffs to better understand what is going on. Timestamp is in seconds (last digit is 1 second).**

> 8'624 | create 16401 (Necropolis) with 28395 (Communique Timer, Necropolis)
`1. Triggers: 28373 (Communique, Necropolis-to-Proxies) every 15 seconds`
> 8'626 | 16386 (Necropolis Relay) casting 28326 (Communique, Relay-to-Camp) every 15 seconds
> 8'637 | create 16136 (Necrotic Shard)
> 8'637 | 16136 (Necrotic Shard) casting 28197 (Camp Type: Ghost/Skeleton)
> 8'637 | 16136 (Necrotic Shard) casting 28346 (Communique Timer, camp)
`1. Triggers: 28345 (Communique Trigger) every 35 seconds`
> 8'637 | 16136 (Necrotic Shard) casting 27887 (Minion Spawner, small)
> 8'637 | 16401 (Necropolis) casting 28373 (Communique, Necropolis-to-Proxies)  every 15 seconds
> 8'637 |  16398 (Necropolis Proxy) casting 28366 (Communique, Proxy-to-Relay) every 15 seconds
> 8'640 | 16136 (Necrotic Shard) casting 28281 (Communique, Camp-to-Relay) every 35 seconds
> 8'643 | 16386 (Necropolis Relay) casting 28365 (Communique, Relay-to-Proxy) every 35 seconds
> 8'643 | 16136 (Necrotic Shard) has now Health 112
> 8'656 | create 16336 (Scourge Invasion Minion, spawner, Ghost/Skeleton)
> 8'656 | create 16356 (Scourge Invasion Minion, finder) casts 28203 (Find Camp Type)
> 8'659 | create 16172 (Damaged Necrotic Shard)
> 8'637 | 16172 (Damaged Necrotic Shard) casting 27887 (Minion Spawner, small)
> 8'637 | 16172 (Damaged Necrotic Shard) casting 27888 (Minion Spawner, Buttress)
> 8'659 | 16172 (Damaged Necrotic Shard) casts 27886 (Disturb Minion Trap, Buttress)
> 8'660 | 16136 (Necrotic Shard) has now Health NULL
> 8'661 | 16230 (Cultist Engineer) casts 28078 (Buttress Channel) on guid 5233 16172 (Damaged Necrotic Shard)
> 8'663 | destroy 16136 (Necrotic Shard)
> 8'673 | 16172 (Damaged Necrotic Shard) casts 28041 (Damage Crystal) every 90 seconds
> 8'673 | 16172 (Damaged Necrotic Shard) casts 28449 (Camp Receives Communique) every 15 seconds
> 8'674 | 16172 (Damaged Necrotic Shard) has now Health 2952
> 9'031 | 16172 (Damaged Necrotic Shard) casts 28351 (Communique, Camp-to-Relay, Death)
> 9'031 | 16172 (Damaged Necrotic Shard) casts 28681 (Soul Revival)
> 9'032 | 16172 (Damaged Necrotic Shard) has now Health 256
> 9'036 | destroy 16172 (Damaged Necrotic Shard)

***********************************************************************************
**communication between npcs**

![Naxx_event_Communique ](https://user-images.githubusercontent.com/357606/103782762-2a1f0a00-5038-11eb-8ca1-72979b326d99.png)

**Works well**

[![PGOOOOO](https://user-images.githubusercontent.com/357606/103835951-ee139580-5087-11eb-8ff4-7e1466b553ca.png)](https://www.youtube.com/watch?v=IHGICd7yjkY)

**Comment by Oroxzy** [comment]
but maybe u guys already sniffed everything 👍

**Comment by Oroxzy** [comment]
I did it!
